# Generated by Django 5.1.2 on 2024-11-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, null=True)),
                ('flag', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('emblem', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_matchday', models.PositiveIntegerField()),
                ('winner', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('utc_date', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('matchday', models.PositiveIntegerField()),
                ('stage', models.CharField(max_length=20, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.area')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.season')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=20, null=True)),
                ('duration', models.CharField(default='REGULAR', max_length=20)),
                ('full_time_home', models.PositiveIntegerField(null=True)),
                ('full_time_away', models.PositiveIntegerField(null=True)),
                ('half_time_home', models.PositiveIntegerField(null=True)),
                ('half_time_away', models.PositiveIntegerField(null=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='football.match')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50, null=True)),
                ('tla', models.CharField(max_length=3)),
                ('crest', models.URLField(null=True)),
                ('address', models.TextField(null=True)),
                ('website', models.URLField(null=True)),
                ('founded', models.PositiveIntegerField(null=True)),
                ('club_colors', models.CharField(max_length=50, null=True)),
                ('venue', models.CharField(max_length=100, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.area')),
                ('running_competitions', models.ManyToManyField(to='football.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='football.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='football.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='football.team'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('contract_start', models.DateField(null=True)),
                ('contract_until', models.DateField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.team')),
            ],
        ),
    ]
